# Generated by Django 4.1.4 on 2022-12-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
