# Generated by Django 4.1.4 on 2022-12-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_bloodbank_department_dispensary_donation_donor_drive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
