# Generated by Django 4.1.4 on 2022-12-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='collected_funds',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drive',
            name='required_funds',
            field=models.IntegerField(default=25000),
            preserve_default=False,
        ),
    ]
