# Generated by Django 4.1.2 on 2022-12-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='used',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='price_per_item',
            field=models.FloatField(default=345),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='plate_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='bloodType',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='medicine',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
