# Generated by Django 4.1.2 on 2022-12-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_donation_used_inventory_price_per_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='phone_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone_no',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
