# Generated by Django 4.1.4 on 2022-12-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_pastdrive_collected_funds'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('inventory_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=250)),
                ('item_count', models.IntegerField()),
                ('price_per_item', models.IntegerField()),
                ('donor_name', models.CharField(max_length=300)),
                ('phone_no', models.CharField(max_length=30)),
                ('donated_amount', models.IntegerField()),
                ('donated_on', models.DateTimeField()),
                ('department', models.CharField(max_length=50)),
                ('drive', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'inventory_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyDonations',
            fields=[
                ('month', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('total_donated', models.IntegerField()),
            ],
            options={
                'db_table': 'monthly_donations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YearlyDonations',
            fields=[
                ('year', models.FloatField(primary_key=True, serialize=False)),
                ('total_donated', models.IntegerField()),
            ],
            options={
                'db_table': 'yearly_donations',
                'managed': False,
            },
        ),
    ]
