# Generated by Django 4.1.4 on 2022-12-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faqs',
        ),
    ]
